[package]
name = "arkadia"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
num = "0.4.3"
rand = "*"
kdtree = "0.7.0"
dary_heap = "0.3.6"

[dev-dependencies]
rand = "*"
kdtree = "0.7.0"

[profile.release]
codegen-units = 1